check filesums if sha1sum is available

diff --git a/summon-arm-toolchain b/summon-arm-toolchain
--- a/summon-arm-toolchain
+++ b/summon-arm-toolchain
@@ -58,6 +58,16 @@ GMP=gmp-5.0.2
 MPFR=mpfr-3.0.1
 MPC=mpc-0.9
 
+SHA1SUMS="ef93235588eb443e4c4a77f229a8d131bccaecc6  binutils-2.21.tar.bz2
+8bf66f7a71534ba564563a0ba0b2517aead8ac30  gcc-4.6.1.tar.bz2
+9b766705f051ffb7321de58f247688b0ae661b98  gcc-core-4.6.1.tar.bz2
+828d99a63e0578879150f5681d234763cff69313  gcc-linaro-4.6-2011.07.tar.bz2
+fefd90275d6decdca00c5c29c533e2ef3d439664  gdb-7.3.tar.bz2
+2968220e1988eabb61f921d11e5d2db5431e0a35  gmp-5.0.2.tar.bz2
+229722d553030734d49731844abfef7617b64f1a  mpc-0.9.tar.gz
+fbf402fc196724ae60ef01eb6ca8490b1ea4db69  mpfr-3.0.1.tar.bz2
+b2269d30ce7b93b7c714b90ef2f40221c2df0fcd  newlib-1.19.0.tar.gz"
+
 ##############################################################################
 # Flags section
 ##############################################################################
@@ -195,6 +205,12 @@ fetch ${GDB} http://ftp.gnu.org/gnu/gdb/${GDB}.tar.bz2
 fetch ${GMP} ftp://ftp.gmplib.org/pub/${GMP}/${GMP}.tar.bz2
 fetch ${MPFR} http://www.mpfr.org/${MPFR}/${MPFR}.tar.bz2
 fetch ${MPC} http://www.multiprecision.org/mpc/download/${MPC}.tar.gz
+
+if which sha1sum > /dev/null; then
+    ( echo "$SHA1SUMS" | sha1sum -c - ) || ( log 'ERROR: Checksum fail!'; exit 1 )
+else
+    log "WARING: skipping checksum checks due to missing sha1sum"
+fi
 
 cd ${SUMMON_DIR}
 
